### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by CreazyBear** [omochi/libwebsockets-ios-build#3]
Hi, I have got same problem with this project. After running the `libwebsockets-ios-build.rb`, I have got the out put files(include and .a). Then I add libwebsocket( include and .a ) and openssl (include and .a )into my xcode project. Every thing seen to be all right. But when I call `lws_create_context(&creationInfo)` or `lws_client_connect_via_info(&connectInfo)` I will got this error.
```
Undefined symbols for architecture i386:
  "_lws_ssl_client_connect2", referenced from:
      _lws_client_socket_service in libwebsockets.a(client.o)
  "_lws_ssl_client_bio_create", referenced from:
      _lws_client_socket_service in libwebsockets.a(client.o)
  "_lws_ssl_client_connect1", referenced from:
      _lws_client_socket_service in libwebsockets.a(client.o)
  "_lws_context_init_server_ssl", referenced from:
      _lws_create_vhost in libwebsockets.a(context.o)
  "_lws_context_init_client_ssl", referenced from:
      _lws_create_vhost in libwebsockets.a(context.o)
      _lws_init_vhost_client_ssl in libwebsockets.a(context.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have no idea where is gong wrong. Would please help me 😄

**Comment by omochi** [comment]
@WalterCreazyBear

If libwebsockets add source code, this issue may happen.
Please open `websockets.xcodeproj` and register source codes in libwebsockets to xcode.

Or, checkout older version `libwebsockets` at Mar 25, 2016. (the time of my last commit)

**Comment by omochi** [comment]
@WalterCreazyBear 
I update build files. Please checkout `dev` branch and try it.
Unfortunately I already stopped my app project which depends on this library.
So I can not test symbol linking issue such like you posted.
If this update would not solve problem, 
I will not support more about this repository trouble.

**Comment by CreazyBear** [comment]
Thank you for your help.
The rb script in dev may runout with some error. 
For the libwebsocket.a ,I have find a ios_64.cmake to make a XCODE project for iOS. And it's work find.
Any way , thank you again.

**Comment by omochi** [comment]
hm...  its strange...


please try this.

```
# start from my repo
$ pwd
/Users/omochi/work/github/omochi/libwebsockets-ios-build

# clear explicitly
$ rm -rf out

# checkout libwebsocket explicitly same with me
$ cd libwebsockets
$ git fetch
$ git checkout cb35969fce3800610db21c0385e316a20d6cc188
$ cd ..

# build
$ ./websockets-ios-build.rb

# check symbol
$ cd out/xcode-build/iphone-simulator-i386/Release-iphonesimulator
$ nm -a libwebsockets.a | grep _lws_ssl_client_connect2
00000428 T _lws_ssl_client_connect2
         U _lws_ssl_client_connect2
```

If you get line `00000428 T _lws_ssl_client_connect2`,
it means symbol is defined in libwebsockets.a.
If it is, I think everything ok.

with full output (command `$ nm -a libwebsocket.a`, no `grep` ), these lines are...

```
...
libwebsockets.a(ssl-client.o):
       	...
00000000 T _lws_ssl_client_bio_create
0000031a T _lws_ssl_client_connect1
00000428 T _lws_ssl_client_connect2
         U _lws_ssl_elaborate_error
         U _lws_ssl_get_error
         U _memset
         U _openssl_websocket_private_data_index
...
libwebsockets.a(client.o):
     	...
         U _lws_ssl_capable_read
         U _lws_ssl_capable_write
         U _lws_ssl_client_bio_create
         U _lws_ssl_client_connect1
         U _lws_ssl_client_connect2
         U _lws_union_transition
        ...
```

It means `ssl-client.o` defines `lws_ssl_client_connect2`.

Actually it in `ssl-client.c` at line `280`

```
int
lws_ssl_client_connect2(struct lws *wsi)
{
	struct lws_context *context = wsi->context;
	struct lws_context_per_thread *pt = &wsi->context->pt[(int)wsi->tsi];
	char *p = (char *)&pt->serv_buf[0];
	char *sb = p;
	int n = 0;
	...
```

How does these in your machine?

**Comment by CreazyBear** [comment]
This is what I get
```
➜  libwebsockets git:(master) git fetch
➜  libwebsockets git:(master) git checkout cb35969fce3800610db21c0385e316a20d6cc188
Note: checking out 'cb35969fce3800610db21c0385e316a20d6cc188'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at cb35969... junzip: import from DomTerm 912add15f3d0aec
➜  libwebsockets git:(cb35969) cd .. 
➜  libwebsockets-ios-build git:(master) ✗ ./websockets-ios-build.rb 
build openssl
Using openssl-1.0.2e.tar.gz
Building openssl-1.0.2e for iPhoneOS 10.2 armv7
  Logfile: /Users/mac/Desktop/libwebsocket-build-dev/libwebsockets-ios-build/OpenSSL-for-iPhone/bin/iPhoneOS10.2-armv7.sdk/build-openssl-1.0.2e.log
  Patch source code...
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
./websockets-ios-build.rb:212:in `exec': exec failed: status=pid 6541 exit 1, command=./build-libssl.sh --no-spinner (RuntimeError)
	from ./websockets-ios-build.rb:103:in `build'
	from ./websockets-ios-build.rb:50:in `main'
	from ./websockets-ios-build.rb:235:in `<main>'
```
And now some thing happend to my net. I can't even clone the git project.😂
```
fetch OpenSSL-for-iPhone
Cloning into 'OpenSSL-for-iPhone'...
remote: Counting objects: 929, done.
Receiving objects:  44% (418/929), 1.08 MiB | 4.00 KiB/s  
```

**Comment by omochi** [comment]
You can retry building OpenSSL by remove `OpenSSL-for-iPhone`

```
$ rm -rf OpenSSL-for-iPhone
$ ./websockets-ios-build.rb
```

**Comment by CreazyBear** [comment]
It's all going success!
The last error is that I have forgot check the dev.
Thank you very much!👍🏻

**Comment by omochi** [comment]
You're welcome 😀
