### ISSUE TITLE
Compile errors in the latest environment

### ISSUE THREAD

**Issue by MinorUncle** [omochi/libwebsockets-ios-build#4]
I used ruby 2.3.3p222 to compile, and there was the following error：

The following build commands failed:
	CompileC out/xcode-build/iphone-armv7/websockets.build/Release-iphoneos/websockets.build/Objects-normal/armv7/ssl-http2.o libwebsockets/lib/ssl-http2.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC out/xcode-build/iphone-armv7/websockets.build/Release-iphoneos/websockets.build/Objects-normal/armv7/base64-decode.o libwebsockets/lib/base64-decode.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
[log dump end]==================
./websockets-ios-build.rb:229:in `wait_with_dot': exec failed: status=pid 18193 exit 65 (RuntimeError)
	from ./websockets-ios-build.rb:182:in `build_target'
	from ./websockets-ios-build.rb:117:in `block in build'
	from ./websockets-ios-build.rb:115:in `each'
	from ./websockets-ios-build.rb:115:in `build'
	from ./websockets-ios-build.rb:50:in `main'
	from ./websockets-ios-build.rb:235:in `<main>'

**Comment by omochi** [comment]
Sorry I don't maintenance this project now.
